server:
  port: 8080

spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}

redis:
  master:
    host: 127.0.0.1
    port: 6379
  slave:
    host: 127.0.0.1
    port: 6479

jwt:
  access-token-header: AccessToken
  refresh-token-header: RefreshToken
  issuer: waterfogsw
  prefix: bearer
  client-secret: ${jwt.client-secret}
  access-token-expiry-seconds: 1800000
  refresh-token-expiry-seconds: 1209600000

oauth2:
  clients:
    google:
      client-id: 843006986889-onjkm3cerb7n62vktp76mre0tk7cpoqs.apps.googleusercontent.com
      client-secret: ${oauth2.clients.google.client-secret}
      redirect-uri: http://localhost:8080/redirect/oauth
  providers:
    google:
      token-uri: https://www.googleapis.com/oauth2/v4/token
      user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
