server:
  port: 8080

spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    url: ${datasource_url}
    username: ${datasource_username}
    password: ${datasource_password}

redis:
  master:
    host: ${redis_master_host}
    port: ${redis_master_port}
  slave:
    host: ${redis_slave_host}
    port: ${redis_slave_port}

jwt:
  access-token-header: AccessToken
  refresh-token-header: RefreshToken
  issuer: waterfogsw
  prefix: bearer
  client-secret: ${token_client_secret}
  access-token-expiry-seconds: 1800000
  refresh-token-expiry-seconds: 1209600000

oauth2:
  clients:
    google:
      client-id: 843006986889-onjkm3cerb7n62vktp76mre0tk7cpoqs.apps.googleusercontent.com
      client-secret: ${google_client_secret}
      redirect-uri: http://localhost:8080/redirect/oauth
  providers:
    google:
      token-uri: https://www.googleapis.com/oauth2/v4/token
      user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
