server:
  port: 8081

spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate.format_sql: true
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}

jwt:
  client-secret: ${jwt.client-secret}
